{{- define "pdf-checklists.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
  {{- with .service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "ClusterIP" .service.type }}
  ports:
    - port: {{ default 80 .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}
---
{{- include "pdf-checklists.service" (merge .Values.frontend (dict "name" .Values.frontend.name)) | nindent 0 }}
---
{{- include "pdf-checklists.service" (merge .Values.backend (dict "name" .Values.backend.name)) | nindent 0 }}
