# Global configurations
global:
  environment: production
  # Common labels will be managed by helper template
  # Default security context for all pods
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  # Default pod annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "metrics"
  # Default resource constraints
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  # Default scheduling rules
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - pdf-checklists
            topologyKey: kubernetes.io/hostname
# Application configurations
frontend:
  name: pdf-checklists-frontend
  image: ghcr.io/desponda/pdf-checklists-frontend
  tag: 0ad463b
  replicas: 2
  # Container configuration
  containerPort: 8080 # nginx-unprivileged uses port 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80 # Service still exposes port 80 externally
    targetPort: 8080 # But forwards to container port 8080
backend:
  name: pdf-checklists-backend
  image: ghcr.io/desponda/pdf-checklists-backend
  tag: 86fb608
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 5000
# Ingress configuration
ingress:
  enabled: false
  className: nginx
  annotations: {}
  host: chart-example.local
  path: /
  pathType: Prefix
  tls: false
