{{/*
Deployment template for pdf-checklists components
*/}}
{{- define "pdf-checklists.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .component.name }}
  labels:
    app: {{ .component.name }}
    {{- include "pdf-checklists.labels" .root | nindent 4 }}
    app.kubernetes.io/component: {{ .component.name }}
spec:
  replicas: {{ .component.replicas }}
  selector:
    matchLabels:
      app: {{ .component.name }}
  template:
    metadata:
      labels:
        app: {{ .component.name }}
      annotations:
        {{- toYaml .root.Values.global.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .root.Values.global.securityContext | nindent 8 }}
      containers:
        - name: {{ .component.name }}
          image: "{{ .component.image }}:{{ .component.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .component.containerPort | default .component.service.port }}
              protocol: TCP
          {{- if eq .component.name $.root.Values.frontend.name }}
          env:
            - name: BACKEND_URL
              value: "http://{{ $.root.Values.backend.name }}:{{ $.root.Values.backend.service.port }}"
          {{- end }}
          {{- if eq .component.name $.root.Values.backend.name }}
          volumeMounts:
            - name: cache-volume
              mountPath: /app/server/cache
          {{- end }}
          resources:
            {{- toYaml .component.resources | nindent 12 }}
      {{- if eq .component.name $.root.Values.backend.name }}
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 500Mi
      {{- end }}
      nodeSelector:
        {{- toYaml .root.Values.global.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .root.Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .root.Values.global.tolerations | nindent 8 }}
{{- end }}
---
# Frontend Deployment
{{- include "pdf-checklists.deployment" (dict "root" . "component" .Values.frontend) | nindent 0 }}
---
# Backend Deployment
{{- include "pdf-checklists.deployment" (dict "root" . "component" .Values.backend) | nindent 0 }}
