{{- define "pdf-checklists.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      {{- with .global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- include "pdf-checklists.deployment" (merge .Values.frontend (dict
  "global" .Values.global
  "nodeSelector" .Values.nodeSelector
  "affinity" .Values.affinity
  "tolerations" .Values.tolerations
  "securityContext" .Values.securityContext
)) | nindent 0 }}
---
{{- include "pdf-checklists.deployment" (merge .Values.backend (dict
  "global" .Values.global
  "nodeSelector" .Values.nodeSelector
  "affinity" .Values.affinity
  "tolerations" .Values.tolerations
  "securityContext" .Values.securityContext
)) | nindent 0 }}
