{{/*
Deployment template for pdf-checklists components
*/}}
{{- define "pdf-checklists.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      annotations:
        {{- toYaml .Values.global.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          resources:
            {{- toYaml .resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
{{- end }}
---
# Frontend Deployment
{{- include "pdf-checklists.deployment" .Values.frontend | nindent 0 }}
---
# Backend Deployment
{{- include "pdf-checklists.deployment" .Values.backend | nindent 0 }}
