{{/*
Service template for pdf-checklists components
*/}}
{{- define "pdf-checklists.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{- end }}
---
{{- include "pdf-checklists.service" .Values.frontend | nindent 0 }}
---
{{- include "pdf-checklists.service" .Values.backend | nindent 0 }}
