{{/*
Service template for pdf-checklists components
*/}}
{{- define "pdf-checklists.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .component.name }}
  labels:
    app: {{ .component.name }}
    {{- toYaml .root.Values.global.labels | nindent 4 }}
    app.kubernetes.io/component: {{ .component.name }}
spec:
  type: {{ .component.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .component.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .component.name }}
{{- end }}
---
{{- include "pdf-checklists.service" (dict "root" . "component" .Values.frontend) | nindent 0 }}
---
{{- include "pdf-checklists.service" (dict "root" . "component" .Values.backend) | nindent 0 }}
